BitirmeProjesi/Controllers/CourseController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BitirmeProjesi.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _notyf;
        public CourseController(ApplicationDbContext context, INotyfService notyf, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _notyf = notyf;
        }

        [Authorize]
        public async Task<IActionResult> MyCourses()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (_context.Course == null)
            {
                _notyf.Error("Eğitim Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            var courses = await _context.Course.Where(c => c.EmployeeCourses.Any(i => i.EmployeeId == user.Id)).ToListAsync();
            return View(courses);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (_context.Course == null)
            {
                _notyf.Error("Eğitim Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            var courses = await _context.Course.ToListAsync();
            return View(courses);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Education(int? id)
        {
            if (id == null)
            {
                _notyf.Error("Eğitim Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                _notyf.Error("Eğitim Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            ViewBag.Workers = _context.Users.Include(p => p.EmployeeCourses).Where(a => a.IsActive == true).OrderBy(s => s.Name).ToList();
            return View(course);
        }

        [HttpPost]
        [Authorize(Roles = "İnsan Kaynakları")]
        public IActionResult Education(int id, string[] userId)
        {
            var course = _context.Course.Include(p => p.EmployeeCourses).FirstOrDefault(i => i.Id == id);
            if (course != null)
            {
                course.EmployeeCourses = userId.Select(emloyeeId => new EmployeeCourses()
                {
                    CourseId = id,
                    EmployeeId = emloyeeId
                }).ToList();
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Create([Bind("Id,Name,Application,Link")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost]
        [Authorize(Roles = "İnsan Kaynakları")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Application,Link")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
          return (_context.Course?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BitirmeProjesi/Controllers/RequestController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BitirmeProjesi.Controllers
{
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _notyf;
        public RequestController(ApplicationDbContext context, INotyfService notyf, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _notyf = notyf;
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Index()
        {
            var data = await _context.Request
               .Include(r => r.ApplicationUser)
               .Where(a => a.Check == false)
               .ToListAsync();
            return View(data);

        }

        [Authorize]
        public async Task<IActionResult> MyRequests()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var data = await _context.Request
               .Include(r => r.ApplicationUser)
               .ToListAsync();
            return View(data);

        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Request? request)
        {
            if (request == null)
            {
                _notyf.Error("İzin Oluşturulamadı!");
                return View("Index", "Home");
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            string time = DateTime.Now.ToString("dd/MM/yyyy HH:mm");

            request.ApplicationUserId = user.Id;

            foreach (var file in request.Files)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var extension = Path.GetExtension(file.FileName);
                var fileModel = new FileModel
                {
                    CreatedOn = time,
                    FileType = file.ContentType,
                    Extension = extension,
                    Name = fileName,
                    RequestId = request.Id
                };
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    fileModel.Data = dataStream.ToArray();
                }
                request.FileList.Add(fileModel);
            }

            _context.Add(request);
            await _context.SaveChangesAsync();
            _notyf.Success("İzin Oluşturuldu!");
            return View(request);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            var request = await _context.Request.Include(a => a.ApplicationUser).Where(b => b.Id == id).FirstOrDefaultAsync();
            if (request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }

            ViewData["User"] = request.ApplicationUser;
            RequestViewModel vm = (new RequestViewModel
            {
                Id = request.Id,
                StartDate = request.StartDate,
                EndDate = request.EndDate,
                ApplicationUser = request.ApplicationUser,
                ApplicationUserId = request.ApplicationUserId,
                Approve = request.Approve,
                Check = request.Check,
                Files = request.Files,
                FileList = request.FileList
            });
            var files = _context.FileModel.Where(a => a.RequestId == id).ToList();
            ViewBag.Files = files;
            return View(vm);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        [HttpPost]
        public async Task<IActionResult> Details(RequestViewModel? request)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            var item = _context.Request.Where(d => d.Id == request.Id).AsNoTracking().FirstOrDefault();
            if (item == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            item.Approve = request.Approve;
            item.Check = true;


            TimeSpan difference = (TimeSpan)(item.EndDate - item.StartDate);
            int days = (int)difference.TotalDays;
            if (item.Approve)
            {
                user.Permission -= days;
                await _userManager.UpdateAsync(user);
                await _context.SaveChangesAsync();
            }

            _context.Update(item);
            _context.Entry(item).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            _notyf.Success("İzin Güncellendi!");
            return RedirectToAction("Index", "Home");
        }
    }
}

BitirmeProjesi/Views/Shared/AdminLTE/_MainNavigation.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-1">
    <br /><br /><br />
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @if (User.IsInRole("İnsan Kaynakları"))
                {
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                İnsan Kaynakları
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-area="" asp-controller="UserRoles" asp-action="Index" class="nav-link">
                                    <p>&emsp;&emsp;Çalışanlar</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="RoleManager" asp-action="Index" class="nav-link">
                                    <p>&emsp;&emsp;Roller</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Department" asp-action="Index" class="nav-link">
                                    <p>&emsp;&emsp;Departmanlar</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                }
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-umbrella-beach"></i>
                        <p>
                            İzin
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Request" asp-action="Create" class="nav-link">
                                <p>&emsp;&emsp;İzin Talebi Oluştur</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Request" asp-action="MyRequests" class="nav-link">
                                <p>&emsp;&emsp;Geçmiş İzinlerim</p>
                            </a>
                        </li>
                        @if (User.IsInRole("İnsan Kaynakları"))
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Request" asp-action="Index" class="nav-link">
                                    <p>&emsp;&emsp;İzin Talepleri</p>
                                </a>
                            </li>
                        }
                    </ul>
                </li>

                <li class="nav-item menu-open">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chalkboard"></i>
                        <p>
                            Eğitim
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Course" asp-action="MyCourses" class="nav-link">
                                <p>&emsp;&emsp;Eğitimlerim</p>
                            </a>
                        </li>
                        @if (User.IsInRole("İnsan Kaynakları"))
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Course" asp-action="Index" class="nav-link">
                                    <p>&emsp;&emsp;Eğitim Listesi</p>
                                </a>
                            </li>
                        }
                    </ul>
                </li>

                <li class="nav-item">
                    <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" class="nav-link" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            Çıkış Yap
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

BitirmeProjesi/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/adminlte.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

BitirmeProjesi/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/css/adminlte.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="dist/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

BitirmeProjesi/Views/Shared/AdminLTE/_TopNavigation.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
	</ul>
	<ul class="navbar-nav">
		@if (SignInManager.IsSignedIn(User))
		{
			Task<ApplicationUser> GetCurrentUserAsync() => UserManager.GetUserAsync(User);
			var user = await GetCurrentUserAsync();
			<li class="nav-item">
				<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index"><b>@user.UserName</b></a>
			</li>
		}
		else
		{
			<li class="nav-item">
				<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Giriş Yap</a>
			</li>
		}
	</ul>
	<ul class="navbar-nav ml-auto">
		<li class="nav-item">
			<a class="nav-link" data-widget="fullscreen" href="#" role="button">
				<i class="fas fa-expand-arrows-alt"></i>
			</a>
		</li>
	</ul>
</nav>