BitirmeProjesi/Controllers/RoleManagerController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BitirmeProjesi.Data;
using BitirmeProjesi.Data.Migrations;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

[Authorize(Roles = "İnsan Kaynakları")]
public class RoleManagerController : Controller
{
    private readonly RoleManager<ApplicationRole> _roleManager;
    private readonly ApplicationDbContext _context;
    private readonly INotyfService _notyf;
    public RoleManagerController(INotyfService notyf, ApplicationDbContext context, RoleManager<ApplicationRole> roleManager)
    {
        _roleManager = roleManager;
        _context = context;
        _notyf = notyf;
    }
    public async Task<IActionResult> Index()
    {
        var roles = await _roleManager.Roles.Include(b => b.Department).ToListAsync();
        ViewData["DepartmentList"] = new SelectList(_context.Set<Department>(), "DepartmentId", "DepartmentName");
        return View(roles);
    }

    [HttpPost]
    public async Task<IActionResult> Create(string roleName, int department)
    {
        if (roleName != null)
        {
            await _roleManager.CreateAsync(new ApplicationRole(roleName.Trim())
            {
                DepartmentId = department
            });
            _notyf.Success("Pozisyon Eklendi");
        }
        return RedirectToAction("Index");
    }
}

BitirmeProjesi/Views/RoleManager/Index.cshtml
@model List<BitirmeProjesi.Models.ApplicationRole>
@{
    ViewData["Title"] = "Pozisyon Yönetimi";
}
<h3>Pozisyon Yönetimi</h3>
<button type="button" class="btn btn-success col-md-6" data-bs-toggle="modal" data-bs-target="#Rol">
    Yeni Pozisyon Ekle
</button>
<div class="modal fade" id="Rol" tabindex="-1" aria-labelledby="RolLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="RolLabel">Yeni Pozisyon Ekle</h5>
            </div>
            <form method="post" asp-action="Create" asp-controller="RoleManager" autocomplete="off">
                <div class="modal-body">
                    <label class="control-label">Pozisyon Adı*</label>
                    <input name="roleName" class="form-control" required />
                    <label class="control-label">Departman Seçiniz</label>
                    <select name="department" class="form-control" asp-items="ViewBag.DepartmentList" required>
                        <option selected="selected" value="">Seçin</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Geri Dön</button>
                    <button type="submit" class="btn btn-primary">Pozisyon Ekle</button>
                </div>
            </form>
        </div>
    </div>
</div>
<table class="table table-striped col-md-6 mt-2">
    <thead>
        <tr>
            <th>Pozisyon Adı</th>
            <th>Departman</th>
            <th>Id</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Name</td>
                <td>@role.Department.DepartmentName</td>
                <td>@role.Id</td>
            </tr>
        }
    </tbody>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation2/4.2.1/bootstrap-confirmation.min.js"></script>