BitirmeProjesi/Models/Request.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BitirmeProjesi.Models
{
    public class Request
    {
        public Request() { 
            Approve = false;
            Check = false;
        }

        public int Id { get; set; }
        [Display(Name = "İzin Başlangıç Tarihi")]
        [Required(ErrorMessage = "Tarih Girin")]
        [DataType(DataType.Date)]
        public DateTime? StartDate { get; set; }

        [Display(Name = "İzin Bitiş Tarihi")]
        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }

        public bool Approve { get; set; }
        public bool Check { get; set; }

        [NotMapped]
        public virtual List<IFormFile>? Files { get; set; } = new List<IFormFile>();
        public virtual List<FileModel>? FileList { get; set; } = new List<FileModel>();
    }
}

BitirmeProjesi/Models/RequestViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BitirmeProjesi.Models
{
    public class RequestViewModel
    {
        public RequestViewModel()
        {
            Approve = false;
            Check = false;
        }

        public int Id { get; set; }
        [Display(Name = "İzin Başlangıç Tarihi")]
        public DateTime? StartDate { get; set; }
        [Display(Name = "İzin Bitiş Tarihi")]
        public DateTime? EndDate { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }
        public bool Approve { get; set; }
        public bool Check { get; set; }
        public virtual List<IFormFile>? Files { get; set; } = new List<IFormFile>();
        public virtual List<FileModel>? FileList { get; set; } = new List<FileModel>();
    }
}

BitirmeProjesi/Controllers/FileController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace BitirmeProjesi.Controllers
{
    public class FileController : Controller
    {
        private readonly ApplicationDbContext _context;
		private readonly INotyfService _notyf;
        private readonly UserManager<ApplicationUser> _userManager;
        public FileController(ApplicationDbContext context, INotyfService notyf, UserManager<ApplicationUser> userManager)
        {
            _context = context;
			_notyf = notyf;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                _notyf.Error("Dosya Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            var file = await _context.FileModel.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (file == null)
            {
                _notyf.Error("Dosya Bulunamadı!");
                return RedirectToAction("HomePage", "Home");
            }
            return File(file.Data, file.FileType, file.Name + file.Extension);
        }
	}
}

BitirmeProjesi/Controllers/RequestController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BitirmeProjesi.Controllers
{
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotyfService _notyf;
        public RequestController(ApplicationDbContext context, INotyfService notyf, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _notyf = notyf;
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Index()
        {
            var data = await _context.Request
               .Include(r => r.ApplicationUser)
               .Where(a => a.Check == false)
               .ToListAsync();
            return View(data);

        }

        [Authorize]
        public async Task<IActionResult> MyRequests()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var data = await _context.Request
               .Include(r => r.ApplicationUser)
               .ToListAsync();
            return View(data);

        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Request? request)
        {
            if (request == null)
            {
                _notyf.Error("İzin Oluşturulamadı!");
                return View("Index", "Home");
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            string time = DateTime.Now.ToString("dd/MM/yyyy HH:mm");

            request.ApplicationUserId = user.Id;

            foreach (var file in request.Files)
            {
                var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                var extension = Path.GetExtension(file.FileName);
                var fileModel = new FileModel
                {
                    CreatedOn = time,
                    FileType = file.ContentType,
                    Extension = extension,
                    Name = fileName,
                    RequestId = request.Id
                };
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    fileModel.Data = dataStream.ToArray();
                }
                request.FileList.Add(fileModel);
            }

            _context.Add(request);
            await _context.SaveChangesAsync();
            _notyf.Success("İzin Oluşturuldu!");
            return View(request);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            var request = await _context.Request.Include(a => a.ApplicationUser).Where(b => b.Id == id).FirstOrDefaultAsync();
            if (request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }

            ViewData["User"] = request.ApplicationUser;
            RequestViewModel vm = (new RequestViewModel
            {
                Id = request.Id,
                StartDate = request.StartDate,
                EndDate = request.EndDate,
                ApplicationUser = request.ApplicationUser,
                ApplicationUserId = request.ApplicationUserId,
                Approve = request.Approve,
                Check = request.Check,
                Files = request.Files,
                FileList = request.FileList
            });
            var files = _context.FileModel.Where(a => a.RequestId == id).ToList();
            ViewBag.Files = files;
            return View(vm);
        }

        [Authorize(Roles = "İnsan Kaynakları")]
        [HttpPost]
        public async Task<IActionResult> Details(RequestViewModel? request)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (request == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            var item = _context.Request.Where(d => d.Id == request.Id).AsNoTracking().FirstOrDefault();
            if (item == null)
            {
                _notyf.Error("İzin Bulunamadı!");
                return RedirectToAction("Index", "Home");
            }
            item.Approve = request.Approve;
            item.Check = true;


            TimeSpan difference = (TimeSpan)(item.EndDate - item.StartDate);
            int days = (int)difference.TotalDays;
            if (item.Approve)
            {
                user.Permission -= days;
                await _userManager.UpdateAsync(user);
                await _context.SaveChangesAsync();
            }

            _context.Update(item);
            _context.Entry(item).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            _notyf.Success("İzin Güncellendi!");
            return RedirectToAction("Index", "Home");
        }
    }
}

BitirmeProjesi/Views/Request/Create.cshtml
@model BitirmeProjesi.Models.Request

@{
    ViewData["Title"] = "İzin Talebi Oluştur";
}

<h3>@ViewData["Title"]</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" required />
            </div>
            <div class="form-group">
                <input asp-for="Files" type="file" multiple />
            </div>
            <div class="form-group">
                <input type="submit" value="Talep Oluştur" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

BitirmeProjesi/Views/Request/Details.cshtml
@model BitirmeProjesi.Models.RequestViewModel

@{
    ViewData["Title"] = "İzin Onayı";
    var files = (IEnumerable<BitirmeProjesi.Models.FileModel>)ViewBag.Files;
    var user = ViewBag.User;
}

<h3>İzin Onayı</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            İsim
        </dt>
        <dd class="col-sm-10">
            @user.Name
        </dd>
        <dt class="col-sm-2">
            İzin Sayısı
        </dt>
        <dd class="col-sm-10">
            @user.Permission Gün
        </dd>
        <dt class="col-sm-2">
            Maaş
        </dt>
        <dd class="col-sm-10">
            @user.Salary ₺
        </dd>
        <dt class="col-sm-2">
            İşe Başlama Tarihi
        </dt>
        <dd class="col-sm-10">
            @user.StartDate
        </dd>
    </dl>
</div>

@if (files.Any())
{
    <hr />
    <h3>Dosyalar</h3>
    <table class="table table-striped table-sm">
        <thead class="thead-light">
            <tr>
                <th class="col-md-5">Dosya Adı</th>
                <th class="col-md-3">Yükleyen</th>
                <th class="col-md-2"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var file in files)
            {
                <tr>
                    <td>@file.Name@file.Extension</td>
                    <td>@file.UploadedBy</td>
                    <td class="text-right">
                        <a type="button" class="btn btn-primary" asp-controller="File" asp-action="Download" asp-route-id="@file.Id">İndir &nbsp <em class="fas fa-file-download"></em></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Details" method="post">
            <input type="checkbox" asp-for="Approve" />
            <label asp-for="Approve">İzni Onayla</label>
            <div class="form-group">
                <input type="submit" value="Gönder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

BitirmeProjesi/Views/Request/Index.cshtml
@model IEnumerable<BitirmeProjesi.Models.Request>

@{
    ViewData["Title"] = "Index";
}

<h3>İzin Talepleri</h3>

<table class="table table-striped col-md-6 mt-3">
    <thead>
        <tr>
            <th>
                Talep Sahibi
            </th>
            <th>
                Kalan İzin Sayısı
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Permission) Gün
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td class="text-right">
                    <a class="btn btn-sm btn-info" asp-action="Details" asp-route-id="@item.Id">Detaylar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BitirmeProjesi/Views/Request/MyRequests.cshtml
@model IEnumerable<BitirmeProjesi.Models.Request>

@{
    ViewData["Title"] = "İzin Taleplerim";
}

<h3>@ViewData["Title"]</h3>

<table class="table table-striped col-md-6 mt-3">
    <thead>
        <tr>
            <th>
                Talep Sahibi
            </th>
            <th>
                Kalan İzin Sayısı
            </th>
            <th>
                Kabul Durumu
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Permission) Gün
                </td>
                @if (!item.Check)
                {
                    <td class="text-secondary">
                        Onay Bekliyor
                    </td>
                }
                else
                {
                    @if (item.Approve)
                    {
                        <td class="text-success">
                            Onaylandı
                        </td>
                    }
                    else
                    {
                        <td class="text-danger">
                            Reddedildi
                        </td>
                    }

                }
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td class="text-right">
                    <a class="btn btn-sm btn-info" asp-action="Details" asp-route-id="@item.Id">Detaylar</a>
                </td>
            </tr>
        }
    </tbody>
</table>