BitirmeProjesi/Models/UserRolesViewModel.cs
namespace BitirmeProjesi.Models
{
    public class UserRolesViewModel
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Selected { get; set; }
    }
}

BitirmeProjesi/Controllers/UserRolesController.cs
using Bitirme.Models;
using BitirmeProjesi.Data;
using BitirmeProjesi.Models;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

[Authorize(Roles = "İnsan Kaynakları")]
public class UserRolesController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;
    private readonly ApplicationDbContext _context;
    public UserRolesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;
        _context = context;
    }
    public async Task<IActionResult> Index()
    {
        var users = await _userManager.Users.ToListAsync();
        var userRolesViewModel = new List<UserViewModel>();
        foreach (ApplicationUser user in users)
        {
            var thisViewModel = new UserViewModel();
            thisViewModel.UserId = user.Id;
            thisViewModel.Email = user.Email;
            thisViewModel.Salary = user.Salary;
            thisViewModel.Permission = user.Permission;
            thisViewModel.IsActive = user.IsActive;
            thisViewModel.StartDate = user.StartDate;
            thisViewModel.EndDate = user.EndDate;
            thisViewModel.Name = user.Name;
            thisViewModel.Roles = await GetUserRoles(user);
            userRolesViewModel.Add(thisViewModel);
        }
        return View(userRolesViewModel);
    }
    private async Task<List<string>> GetUserRoles(ApplicationUser user)
    {
        return new List<string>(await _userManager.GetRolesAsync(user));
    }
    public async Task<IActionResult> Manage(string userId)
    {
        ViewBag.userId = userId;
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
            return View("NotFound");
        }
        ViewBag.UserName = user.UserName;
        var model = new List<UserRolesViewModel>();
        foreach (var role in _roleManager.Roles)
        {
            var userRolesViewModel = new UserRolesViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name
            };
            if (await _userManager.IsInRoleAsync(user, role.Name))
            {
                userRolesViewModel.Selected = true;
            }
            else
            {
                userRolesViewModel.Selected = false;
            }
            model.Add(userRolesViewModel);
        }
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> Manage(List<UserRolesViewModel> model, string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return View();
        }
        var roles = await _userManager.GetRolesAsync(user);
        var result = await _userManager.RemoveFromRolesAsync(user, roles);
        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot remove user existing roles");
            return View(model);
        }
        result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
        if (!result.Succeeded)
        {
            ModelState.AddModelError("", "Cannot add selected roles to user");
            return View(model);
        }
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(string userId)
    {
        if (userId == null)
        {
            return RedirectToAction("Index", "Home");
        }
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return RedirectToAction("Index", "Home");
        }
        var thisViewModel = new UserViewModel();
        thisViewModel.UserId = user.Id;
        thisViewModel.Email = user.Email;
        thisViewModel.PhoneNumber = user.PhoneNumber;
        thisViewModel.Salary = user.Salary;
        thisViewModel.Permission = user.Permission;
        thisViewModel.IsActive = user.IsActive;
        thisViewModel.StartDate = user.StartDate;
        thisViewModel.EndDate = user.EndDate;
        thisViewModel.Name = user.Name;
        return View(thisViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UserViewModel userView)
    {
        var user = await _userManager.FindByIdAsync(userView.UserId);
        user.Name = userView.Name;
        user.Email = userView.Email;
        user.Salary = userView.Salary;
        user.Permission = userView.Permission;
        user.IsActive = userView.IsActive;
        user.EndDate = userView.EndDate;
        user.StartDate = userView.StartDate;
        user.PhoneNumber = userView.PhoneNumber;
        await _userManager.UpdateAsync(user);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }

    public ActionResult ExportToExcel()
    {
        System.Data.DataTable table = GetData();
        string fileName = "Çalışan Listesi.xlsx";
        using (XLWorkbook wb = new XLWorkbook())
        {
            wb.Worksheets.Add(table);
            using (MemoryStream stream = new MemoryStream())
            {
                wb.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }
    }

    private System.Data.DataTable GetData()
    {
        System.Data.DataTable table = new System.Data.DataTable();
        table.TableName = "Çalışan Listesi";
        table.Columns.Add("Çalışan İsmi");
        table.Columns.Add("Çalışan E-Postası");
        var data = _userManager.Users.ToList();
        for (int i = 0; i < data.Count(); i++)
        {
            table.Rows.Add(data[i].Name, data[i].Email);
        }
        table.AcceptChanges();
        return table;
    }
}

BitirmeProjesi/Views/UserRoles/Edit.cshtml
@model Bitirme.Models.UserViewModel
@{
    ViewData["Title"] = "Personeli Düzenle";
}
<h3>@ViewData["Title"]</h3>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="StartDate"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label">İsim</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-Posta</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label">Maaş(₺)</label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label">Telefon Numarası</label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Permission" class="control-label">İzin Hakkı (Gün)</label>
                <input asp-for="Permission" class="form-control" />
                <span asp-validation-for="Permission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    Kaydet
                </button>
                <a class="btn btn-danger" href="javascript:void(0);" onclick="history.go(-1);">Geri Dön</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BitirmeProjesi/Views/UserRoles/Index.cshtml
@using Bitirme.Models
@model List<Bitirme.Models.UserViewModel>
@{
    ViewData["Title"] = "Personel Yönetimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 class="d-inline-block">@ViewData["Title"]</h3>
<div class="float-right d-inline-block">
    <a class="btn btn-md btn-success" asp-area="Identity" asp-page="/Account/Register">Yeni Personel Ekle</a>
    <a class="btn btn-md btn-primary" asp-action="ExportToExcel">Excel'e Aktar</a>
</div>
<table class="table table-striped mt-2">
    <thead >
        <tr>
            <th>İsim</th>
            <th>İşe Başlama Tarihi</th>
            <th>Maaş</th>
            <th>E-Posta</th>
            <th>Pozisyon</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Name</td>
                <td>@user.StartDate</td>
                <td>@user.Salary</td>
                <td>@user.Email</td>
                <td>@string.Join(" , ", user.Roles.ToList())</td>
                <td class="text-right">
                    <a class="btn btn-primary" asp-controller="UserRoles" asp-action="Manage" asp-route-userId="@user.UserId">Pozisyonu Düzenle</a>
                    <a class="btn btn-primary" asp-controller="UserRoles" asp-action="Edit" asp-route-userId="@user.UserId">Bilgileri Düzenle</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BitirmeProjesi/Views/UserRoles/Manage.cshtml
@model List<UserRolesViewModel>
@{
    ViewData["Title"] = "Rolleri Düzenle";
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <h2> @ViewBag.UserName için Rolleri Düzenle</h2>

        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].Selected">
                        @Model[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Güncelle" class="btn btn-success"
                   style="width:auto" />
        </div>
    </div>
</form>